---
# ./playbook.sh launch-jenkins.yml -e env=ops -e hostname=jenkins.ops.acme.net

- import_playbook: plays/validate-env.yml
- import_playbook: plays/validate-hostname.yml

- name: Launch instance
  hosts: localhost
  connection: local

  roles:

    - role: launch
      tags: launch
      image_type: ubuntu16
      image_owner: vendor
      launch_group: jenkins
      exact_count: 1
      count_tag:
        env: "{{ env }}"
        project: ops
        role: jenkins
        hostname: "{{ hostname }}"
      subnets: "{{ subnet_ids[region].ops.private }}"
      instance:
        instance_profile_name: "{{ customer }}-ops-jenkins"
        security_groups:
          - "{{ customer }}-ops-all"
          - "{{ customer }}-ops-jenkins"
        tags:
          Name: "{{ customer }}-ops-jenkins"
          role: jenkins
          project: ops
          hostname: "{{ hostname }}"
        type: t2.small
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 8
            delete_on_termination: yes
          - device_name: /dev/xvdf
            volume_type: gp2
            volume_size: 20
            delete_on_termination: no


- import_playbook: plays/install-python.yml
  vars:
    hosts_pattern: jenkins


- name: Prepare additional EBS volumes
  hosts: jenkins
  become: yes
  roles:
    - role: mount-ebs
      volume:
        device_name: /dev/xvdf
        mount_point: /var/lib/jenkins


- import_playbook: plays/set-hostname.yml
  vars:
    hosts_pattern: jenkins


- import_playbook: plays/register-internal-dns.yml
  vars:
    hosts_pattern: jenkins
    project: ops


- import_playbook: plays/register-elb-target.yml
  vars:
    hosts_pattern: jenkins
    target_group: "{{ customer }}-ops-jenkins"


- import_playbook: configure-jenkins.yml


# vim: set ft=ansible ts=2 sts=2 sw=2 et:
