---
# TODO: add root password and encrypt
root_password_crypted: "$6$rounds=60000$KAq3EBYXKubDEKE8$u7Klbovlt.lBa0ZNtWf3aZfT.oyUGZXi33pMow1AwEa9Sx6.hVKjqkhrk4cpeS60e42lKU6ClWaVPB8vFLydB."

# vim: set ft=ansible ts=2 sts=2 sw=2 et:
