---
- name: Install packages (Debian)
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - build-essential
    - git
    - libbz2-dev
    - libreadline-dev
    - libsqlite0-dev
    - libsqlite3-dev
    - libssl-dev
    - python-dev
    - python-pip

- name: Install Python packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - boto
    - boto3
    - jinja2
    - netaddr
    - pycrypto
    - pyyaml

- name: Install Ansible
  pip:
    name: ansible
    version: "{{ ansible_max_version }}"
    state: present

- name: Create ansible user
  user:
    name: ansible
    home: /usr/local/ansible
    createhome: yes
    shell: /bin/bash
    state: present

- block:
    - name: Create jenkins directory
      file:
        path: "~/jenkins"
        state: directory

    - name: Create .ssh directory
      file:
        path: "~/.ssh"
        state: directory

    - name: Allow CI login
      lineinfile:
        dest: "~/.ssh/authorized_keys"
        line: "{{ ci_ssh_public_key }}"
        create: yes
        state: present

    - name: Configure SSH
      template:
        src: ssh_config.j2
        dest: "~/.ssh/config"

  become: yes
  become_user: ansible

# vim: set ft=ansible ts=2 sts=2 sw=2 et:
